# Allow compute credits usage by collaborators and bors.
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

Linux_task:
  container:
    matrix:
      - image: ruby:2.7-slim
      - image: ruby:3.0-slim
      - image: ruby:3.1-slim
      - image: ruby:3.2-slim
  install_script:
    - gem install bundler
    - bundle install
  script:
    - ruby --version
    - bundle exec rake spec

task:
  name: CI Success
  container: {image: "busybox"}
  depends_on:
    - Linux
